local Stack = require("luacore").types.stack

describe("Stack", function()
	describe(":Push", function()
		it("should push items onto the stack", function()
			local s1 = Stack()

			s1:PushBack({ name = "Alice", role = "Developer" })
			s1:PushBack({ name = "Bob", title = "CTO" })
			assert.are.equals(2, s1:Size())

			local s2 = Stack()
			s2:PushBack({ name = "Charlie", company = "TechCorp" })
			s2:PushBack({ name = "Diana", skills = "Python" })
			s2:PushBack({ name = "Ethan", role = "Manager" })
			assert.are.equals(3, s2:Size())

			local s3 = Stack()
			assert.are.equals(0, s3:Size())

			local s4 = Stack()
			s4:PushBack({ name = "Frank", experience = "5 years" })
			s4:PushBack({ name = "Grace", education = "MBA" })
			s4:PushBack({ name = "Henry", location = "New York" })
			s4:PushBack({ name = "Ivy", industry = "Finance" })
			assert.are.equals(4, s4:Size())

			local s4 = Stack()
			s4:PushBack({ name = "Jack", connections = 500 })
			s4:PushBack({ name = "Kelly", endorsements = 50 })
			assert.are.equals(2, s4:Size())
		end)
	end)
	describe(":Back And :PopBack", function()
		it("should return the item at the top of the stack", function()
			local s1 = Stack()

			s1:PushBack({ name = "Alice", role = "Developer" })
			s1:PushBack({ name = "Bob", role = "Designer" })
			assert.are.equals(2, s1:Size())
			assert.are.same({ name = "Bob", role = "Designer" }, s1:Back())
			assert.are.same({ name = "Bob", role = "Designer" }, s1:PopBack())
			assert.are.equals(1, s1:Size())

			local s2 = Stack()
			assert.is_nil(s2:Back())

			local s3 = Stack()
			s3:PushBack({ name = "Charlie", company = "TechCorp" })
			s3:PushBack({ name = "David", skills = { "Python", "JavaScript" } })
			assert.are.same({ name = "David", skills = { "Python", "JavaScript" } }, s3:PopBack())
			assert.are.same({ name = "Charlie", company = "TechCorp" }, s3:PopBack())
			assert.is_nil(s3:Back())

			local s4 = Stack()
			s4:PushBack({ name = "Eve", role = "Manager", years = 5 })
			assert.are.same({ name = "Eve", role = "Manager", years = 5 }, s4:Back())
			s4:PushBack({ name = "Frank", role = "DevOps" })
			assert.are.same(2, s4:Size())
			assert.are.same({ name = "Frank", role = "DevOps" }, s4:PopBack())
			assert.are.same({ name = "Eve", role = "Manager", years = 5 }, s4:PopBack())
			assert.is_nil(s4:Back())
		end)
	end)
end)
